#!/usr/bin/env python3
"""The Codex render tool — one renderer for BOTH Codex adapter surfaces (eADR-0034).

The canonical operator surfaces are authored ONCE, on the Claude side (.claude/agents/*.md and
.claude/skills/engine-*/SKILL.md); Codex requires the same material in its own native homes
(.codex/agents/*.toml and .agents/skills/engine-*/). This tool renders those homes as COMMITTED
files from the canonical sources — never symlinks, never hand-copies — and its `check` verb is the
drift gate: a render that no longer matches its source, or an engine-prefixed render with no source,
is a finding (the codex-agent coherence check runs it in CI). Editing a rendered file by hand is
always wrong; edit the Claude source and regenerate:

    uv run --directory .engine --frozen -- python tools/codex_gen.py generate
    uv run --directory .engine --frozen -- python tools/codex_gen.py check

Render rules (the whole mapping, so review needs no second source):
  AGENTS (.claude/agents/<name>.md -> .codex/agents/<name>.toml):
    - name/description from the frontmatter; the prose body becomes `developer_instructions`,
      prefixed with rendered routing lines for what the TOML cannot carry structurally (the output
      contract; the read-only floor; a no-shell line when the source denylists Bash).
    - `sandbox_mode = "read-only"` always (every current persona is a report-only reviewer).
    - `model` is NEVER emitted (a pinned model id in a persona file rots — eADR-0034);
      `model_reasoning_effort` maps the demand tier (judgment -> high, mechanical -> low).
  SKILLS (.claude/skills/engine-*/ -> .agents/skills/engine-*/):
    - frontmatter narrows to the two keys Codex reads (name = the directory slug, description);
      the Claude governance flags stay home. The companion `agents/openai.yaml` carries the one
      governance value Codex acts on, MIRRORED from the source's `invocation`: an operator-typed
      skill renders `policy.allow_implicit_invocation: false` (the self-election safety property),
      and a model-reachable one renders true — a blanket false would ship a model-auto capability
      on Claude and silently disable it on Codex.
    - the body is the Claude body with the typed prefix rewritten (/engine-x -> $engine-x) and the
      Claude session flag dropped (the engine resolves the session itself on Codex).
    - every engine skill is rendered; there is no exclusion. (The routine backend — the set-routine
      stance-entry — shipped, so `engine-routine` now has its Codex twin like the rest.)
"""
from __future__ import annotations
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import validate  # noqa: E402

AGENT_SRC_GLOB = os.path.join(".claude", "agents", "engine-*.md")
_AGENT_SRC_ALL = os.path.join(".claude", "agents", "*.md")
SKILL_SRC_ROOT = os.path.join(".claude", "skills")
AGENT_OUT_DIR = os.path.join(".codex", "agents")
SKILL_OUT_ROOT = os.path.join(".agents", "skills")

SKILL_EXCLUDE = frozenset()   # no exclusions — every engine skill has a Codex twin (the routine backend shipped)

_EFFORT_BY_TIER = {"judgment": "high", "mechanical": "low"}

_SESSION_FLAG_RE = re.compile(r'\s*--session\s+"\$\{CLAUDE_CODE_SESSION_ID\}"')
# A typed verb reference is a /engine-… NOT preceded by a word character (so a path segment like
# `.claude/skills/engine-x` never rewrites, while a backticked `/engine-x` does).
_TYPED_PREFIX_RE = re.compile(r"(?<!\w)/(engine-[a-z-]+)")

_TOML_BANNER = ("# GENERATED by .engine/tools/codex_gen.py from {src} — edit that source and "
                "regenerate; never edit this file by hand.")
_MD_BANNER = ("<!-- GENERATED by .engine/tools/codex_gen.py from {src} — edit that source and "
              "regenerate; never edit this file by hand. -->")
_OPENAI_YAML_TYPED = ("# GENERATED by .engine/tools/codex_gen.py — this engine command is operator-typed:\n"
                      "# the model must never invoke it on its own; the operator's explicit $-invocation still works.\n"
                      "policy:\n"
                      "  allow_implicit_invocation: false\n")

_OPENAI_YAML_MODEL_STARTABLE = (
    "# GENERATED by .engine/tools/codex_gen.py — this engine command is model-startable:\n"
    "# its Claude source declares an invocation the model may reach itself, so the Codex twin matches rather\n"
    "# than silently disabling the capability on one runtime; the operator's $-invocation works too.\n"
    "policy:\n"
    "  allow_implicit_invocation: true\n")

# The governance values that decide the policy. Model-reachability must be DECLARED, never inferred from an
# omission: on the Claude side an omitted invocation means model-auto (the platform default), but reading it
# that way here would make "deliberately model-reachable" indistinguishable from "the author forgot the key",
# and the failure would silently hand the model a command it was never meant to start. So this fails CLOSED —
# anything that does not explicitly declare reachability renders operator-only.
_MODEL_REACHABLE = ("model-auto", "model-only")


def skill_policy(invocation) -> str:
    """The Codex `agents/openai.yaml` for a skill whose Claude source declares `invocation`. Keeping this a
    function of the SOURCE (rather than a constant) is what lets a model-reachable skill exist at all:
    hard-coding the operator-only policy for every skill would ship such a capability on Claude and quietly
    disable it on Codex, a runtime-partial build. The self-election safety property is preserved and defaults
    toward it — only an explicit model-auto / model-only declaration renders implicit invocation allowed."""
    return _OPENAI_YAML_MODEL_STARTABLE if invocation in _MODEL_REACHABLE else _OPENAI_YAML_TYPED


def _split_frontmatter(path: str):
    """(frontmatter dict, body text) for a prose source file."""
    fm = validate.frontmatter(path)
    text = validate.read(path)
    m = re.match(r"\A---\n.*?\n---\n", text, re.DOTALL)
    return fm, text[m.end():] if m else text


def _routing_lines(fm: dict) -> str:
    disallowed = fm.get("disallowedTools") or []
    if isinstance(disallowed, str):
        disallowed = [t.strip() for t in disallowed.split(",")]
    lines = [f"Output contract: report every finding on the {fm.get('output-contract')} shape "
             f"(severity, message, location).",
             "Permissions floor: read-only. You review and report; you never edit files, commit, "
             "push, open pull requests, or resolve your own findings."]
    if "Bash" in disallowed:
        lines.append("Do not run shell commands; work from reading alone.")
    return "\n".join(lines)


def render_agent(src_path: str, root: str | None = None) -> str:
    """One persona's committed TOML render. `root` anchors the banner's source path (the render
    base — defaults to the live repo)."""
    fm, body = _split_frontmatter(src_path)
    rel_src = os.path.relpath(src_path, root or validate.ROOT).replace(os.sep, "/")
    instructions = _routing_lines(fm) + "\n\n" + body.strip() + "\n"
    # The reasoning effort is the one the bindings stamped into the persona's frontmatter (model-bindings.json
    # -> agent_bindings render -> frontmatter), so both platforms read one rendered source; the tier map is a
    # fallback for a persona not yet stamped. Codex still emits NO model — a pinned model id in a persona rots.
    effort = fm.get("effort") or _EFFORT_BY_TIER.get(fm.get("model-tier"), "high")
    return "\n".join([
        _TOML_BANNER.format(src=rel_src),
        f"name = {json.dumps(fm.get('name'))}",
        f"description = {json.dumps(fm.get('description'))}",
        'sandbox_mode = "read-only"',
        f'model_reasoning_effort = "{effort}"',
        f"developer_instructions = {json.dumps(instructions)}",
        "",
    ])


def render_skill(src_dir: str, root: str | None = None):
    """One skill's committed Codex render: (SKILL.md text, agents/openai.yaml text). `root`
    anchors the banner's source path (the render base — defaults to the live repo)."""
    src_path = os.path.join(src_dir, "SKILL.md")
    fm, body = _split_frontmatter(src_path)
    slug = os.path.basename(src_dir)
    rel_src = os.path.relpath(src_path, root or validate.ROOT).replace(os.sep, "/")
    body = _SESSION_FLAG_RE.sub("", body)
    body = _TYPED_PREFIX_RE.sub(r"$\1", body)
    text = "\n".join([
        "---",
        f"name: {slug}",
        f"description: {fm.get('description')}",
        "---",
        "",
        _MD_BANNER.format(src=rel_src),
        "",
        body.strip(),
        "",
    ])
    return text, skill_policy(fm.get("invocation"))


def _agent_sources(root: str) -> list:
    # Every persona in .claude/agents/ is engine-authored today; render them all, engine-prefixed
    # or not (the roster is the source directory, so a new persona gets its twin automatically).
    return sorted(glob.glob(os.path.join(root, _AGENT_SRC_ALL)))


def _skill_sources(root: str) -> list:
    out = []
    for src_dir in sorted(glob.glob(os.path.join(root, SKILL_SRC_ROOT, "engine-*"))):
        slug = os.path.basename(src_dir)
        if slug in SKILL_EXCLUDE or not os.path.isfile(os.path.join(src_dir, "SKILL.md")):
            continue
        out.append(src_dir)
    return out


def expected_renders(root: str | None = None) -> dict:
    """{relative output path: rendered content} — the complete render set, the single source both
    generate() and check() consume so they can never disagree."""
    base = root or validate.ROOT
    out = {}
    for src in _agent_sources(base):
        name = os.path.splitext(os.path.basename(src))[0]
        out[os.path.join(AGENT_OUT_DIR, f"{name}.toml")] = render_agent(src, base)
    for src_dir in _skill_sources(base):
        slug = os.path.basename(src_dir)
        text, policy = render_skill(src_dir, base)
        out[os.path.join(SKILL_OUT_ROOT, slug, "SKILL.md")] = text
        out[os.path.join(SKILL_OUT_ROOT, slug, "agents", "openai.yaml")] = policy
    return out


def _orphan_renders(base: str, expected: dict) -> list:
    """Engine-prefixed rendered files on disk that generation would NOT produce — a hand-dropped or
    stale twin (e.g. a rendered skill whose Claude source was removed, or an excluded one)."""
    present = set()
    for path in glob.glob(os.path.join(base, AGENT_OUT_DIR, "engine-*.toml")):
        present.add(os.path.relpath(path, base))
    for pattern in ("SKILL.md", os.path.join("agents", "openai.yaml")):
        for path in glob.glob(os.path.join(base, SKILL_OUT_ROOT, "engine-*", pattern)):
            present.add(os.path.relpath(path, base))
    return sorted(present - set(expected))


def generate(root: str | None = None) -> list:
    """Write every render; returns the relative paths written (changed or created)."""
    base = root or validate.ROOT
    changed = []
    for rel, content in sorted(expected_renders(base).items()):
        path = os.path.join(base, rel)
        current = validate.read(path) if os.path.exists(path) else None
        if current != content:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            changed.append(rel)
    return changed


def check(root: str | None = None) -> list:
    """The drift findings: every render that is missing or stale against its canonical source, and
    every engine-prefixed render with no source. Empty list = in sync."""
    base = root or validate.ROOT
    problems = []
    expected = expected_renders(base)
    for rel, content in sorted(expected.items()):
        path = os.path.join(base, rel)
        if not os.path.exists(path):
            problems.append(f"'{rel}' is missing — its canonical source expects this render; run "
                            f"codex_gen.py generate and commit.")
        elif validate.read(path) != content:
            problems.append(f"'{rel}' does not match its canonical source — it was hand-edited or "
                            f"the source changed without regenerating; run codex_gen.py generate "
                            f"and commit (edit the .claude/ source, never this render).")
    for rel in _orphan_renders(base, expected):
        problems.append(f"'{rel}' has no canonical source to render from — remove it, or add the "
                        f"missing .claude/ source (renders are generated, never hand-authored).")
    return problems


def main(argv: list) -> int:
    if argv and argv[0] == "generate":
        changed = generate()
        if changed:
            print("Rendered the Codex twins of the canonical Claude surfaces:")
            for rel in changed:
                print(f"  - {rel}")
        else:
            print("Nothing to render - every Codex twin already matches its canonical source.")
        return 0
    if argv and argv[0] == "check":
        problems = check()
        for p in problems:
            print(p)
        if not problems:
            print("Every Codex render matches its canonical Claude source.")
        return 1 if problems else 0
    print("usage: codex_gen.py [generate | check]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
